// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTx3sj0IixbeyTnsSWFgFNX91o7c-egfE',
    appId: '1:441889478215:web:19d8fb406d2bd9dde6c362',
    messagingSenderId: '441889478215',
    projectId: 'armzup-app',
    authDomain: 'armzup-app.firebaseapp.com',
    storageBucket: 'armzup-app.firebasestorage.app',
    measurementId: 'G-YM3T6L1X3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMh1gzUZ9BFhBTdK35T42Y4xig20SQ0KQ',
    appId: '1:441889478215:android:023b6e943a20a58be6c362',
    messagingSenderId: '441889478215',
    projectId: 'armzup-app',
    storageBucket: 'armzup-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKbPidjkoFyKp5aESlLGPlUwqZkUjw_DA',
    appId: '1:441889478215:ios:393bcc7380f81d3ae6c362',
    messagingSenderId: '441889478215',
    projectId: 'armzup-app',
    storageBucket: 'armzup-app.firebasestorage.app',
    androidClientId: '441889478215-8rbtobmopkpe1806dg2ifiocoaonsq41.apps.googleusercontent.com',
    iosClientId: '441889478215-hbiu5nhsqp1b2i419mpepc1vunkeinea.apps.googleusercontent.com',
    iosBundleId: 'armzup.com.armzup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKbPidjkoFyKp5aESlLGPlUwqZkUjw_DA',
    appId: '1:441889478215:ios:393bcc7380f81d3ae6c362',
    messagingSenderId: '441889478215',
    projectId: 'armzup-app',
    storageBucket: 'armzup-app.firebasestorage.app',
    androidClientId: '441889478215-8rbtobmopkpe1806dg2ifiocoaonsq41.apps.googleusercontent.com',
    iosClientId: '441889478215-hbiu5nhsqp1b2i419mpepc1vunkeinea.apps.googleusercontent.com',
    iosBundleId: 'armzup.com.armzup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTx3sj0IixbeyTnsSWFgFNX91o7c-egfE',
    appId: '1:441889478215:web:719423debf62e527e6c362',
    messagingSenderId: '441889478215',
    projectId: 'armzup-app',
    authDomain: 'armzup-app.firebaseapp.com',
    storageBucket: 'armzup-app.firebasestorage.app',
    measurementId: 'G-QP5R812Z4C',
  );

}